apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ids-basecamp-clearinghouse.fullname" . }}-app
  labels:
    {{- include "ids-basecamp-clearinghouse.ch-app.labels" . | nindent 4 }}
data:
  config.toml: |-
    log_level = {{ .Values.app.logLevel | quote }} # TRACE, DEBUG, INFO, WARN, ERROR
    document_database_url={{ .Values.app.documentDatabaseUrl | quote }}
    process_database_url={{ .Values.app.processDatabaseUrl | quote }}
    keyring_database_url={{ .Values.app.keyringDatabaseUrl | quote }}
    clear_db = false
    signing_key = "keys/private_key.der" # Optional
    performance_tracing = false
---
# Based on EDC milestone-8
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ids-basecamp-clearinghouse.fullname" . }}-edc
  labels:
    {{- include "ids-basecamp-clearinghouse.ch-edc.labels" . | nindent 4 }}
data:
  # Connector Host Name
  MY_EDC_FQDN: {{ printf "clearinghouse.%s.prod.truzztbox.org" .Values.ingress.truzztboxId }}
  # Connector Technical Name
  MY_EDC_NAME_KEBAB_CASE: {{ .Values.edc.name }}
  # Connector Localized Name / Title
  MY_EDC_TITLE: {{ .Values.edc.title }}
  # Connector Description Text
  MY_EDC_DESCRIPTION: {{ .Values.edc.description }}
  # Connector Curator
  # The company using the EDC Connector, configuring data offers, etc.
  MY_EDC_CURATOR_URL: {{ .Values.edc.curator.url }}
  MY_EDC_CURATOR_NAME: {{ .Values.edc.curator.name }}
  # Management API Key
  EDC_API_AUTH_KEY: {{ .Values.edc.api.authKey }}
  # Connector Maintainer
  # The company hosting the EDC Connector
  MY_EDC_MAINTAINER_URL: "https://truzzt.com"
  MY_EDC_MAINTAINER_NAME: "truzzt GmbH"
  # DAPS URL
  EDC_OAUTH_TOKEN_URL: {{ .Values.mds.oauthTokenUrl }}
  EDC_OAUTH_PROVIDER_JWKS_URL: {{ .Values.mds.oauthProviderUrl }}
  # DAPS Credentials
  EDC_OAUTH_CLIENT_ID: {{ .Values.edc.oauth.clientId }}
  EDC_KEYSTORE: /resources/vault/edc/keystore.jks
  EDC_KEYSTORE_PASSWORD: 'password'
  EDC_OAUTH_CERTIFICATE_ALIAS: "1"
  EDC_OAUTH_PRIVATE_KEY_ALIAS: "1"
  TRUZZT_CLEARINGHOUSE_JWT_AUDIENCE: {{ .Values.jwt.audiance | quote }}
  TRUZZT_CLEARINGHOUSE_JWT_ISSUER: {{ .Values.jwt.issuer | quote }}
  TRUZZT_CLEARINGHOUSE_JWT_SIGN_SECRET: {{ .Values.jwt.sharedSecret | quote }}
  TRUZZT_CLEARINGHOUSE_JWT_EXPIRES_AT: "30"
  TRUZZT_CLEARINGHOUSE_APP_BASE_URL: {{ include "ids-basecamp-clearinghouse.fullname" . }}-app:8080
