apiVersion: v1
kind: Secret
metadata:
metadata:
  name: {{ include "ids-basecamp-clearinghouse.fullname" . }}-edc
  labels:
    {{- include "ids-basecamp-clearinghouse.ch-edc.labels" . | nindent 4 }}
type: Opaque
data:
  keystore.jks: {{ .Values.edc.keystore.contentB64 }}
  vault.properties: {{ .Values.edc.vaultB64 }}
---
apiVersion: v1
kind: Secret
metadata:
metadata:
  name: {{ include "ids-basecamp-clearinghouse.fullname" . }}-app
  labels:
    {{- include "ids-basecamp-clearinghouse.ch-app.labels" . | nindent 4 }}
type: Opaque
data:
  private_key.der: {{ .Values.app.privateKeyB64 }}
